//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IJupiterConnectionService")]
public interface IJupiterConnectionService {
    
    // CODEGEN: Parameter 'selectResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJupiterConnectionService/select", ReplyAction="http://tempuri.org/IJupiterConnectionService/selectResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    selectResponse select(selectRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class selectRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string sql;
    
    public selectRequest() {
    }
    
    public selectRequest(string sql) {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="selectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class selectResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SelectResult selectResult;
    
    public selectResponse() {
    }
    
    public selectResponse(SelectResult selectResult) {
        this.selectResult = selectResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IJupiterConnectionServiceChannel : IJupiterConnectionService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class JupiterConnectionServiceClient : System.ServiceModel.ClientBase<IJupiterConnectionService>, IJupiterConnectionService {
    
    public JupiterConnectionServiceClient() {
    }
    
    public JupiterConnectionServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public JupiterConnectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JupiterConnectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JupiterConnectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    selectResponse IJupiterConnectionService.select(selectRequest request) {
        return base.Channel.select(request);
    }
    
    public SelectResult select(string sql) {
        selectRequest inValue = new selectRequest();
        inValue.sql = sql;
        selectResponse retVal = ((IJupiterConnectionService)(this)).select(inValue);
        return retVal.selectResult;
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "0.1.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/JupiterConnection")]
public partial class SelectResult {
    
    private System.Data.DataSet dataSetResultField;
    
    private string errorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Data.DataSet DataSetResult {
        get {
            return this.dataSetResultField;
        }
        set {
            this.dataSetResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}


